# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

post:
    resource: "@BabbelUserBundle/Controller/PostController.php"
    type:     annotation